// client/src/components/cards/DiscardPile.tsx
import { useEffect, useRef, useState } from 'react'
import { motion } from 'framer-motion'
import { CardDTO, CardColor } from '../../types/protocol'
import { Card } from './Card'
import { ACTIVE_RING, SUIT_PAINT, SUIT_ANGLE_DEG, CARD_W, CARD_H, cardKey, flightFor } from './cardTheme'
import { SuitMark } from './suitMark'
import { useColorAssist } from '../../hooks/useColorAssist'
import { discardPosition } from './layout'
import styles from './DiscardPile.module.css'

interface Props {
  card: CardDTO | null
  activeColor: CardColor
  pendingDraw: number
  width: number
  height: number
  /** Vertical space claimed by the opponent seats — the piles follow the felt. */
  topReserve?: number
}

// Fixed tilts for the cards buried under the top one. Static rather than random
// so the pile doesn't reshuffle itself on every render.
const UNDER_LAYERS = [
  { rotate: -4, dx: -2, dy: 1, opacity: 0.28 },
  { rotate: 3, dx: 1, dy: -1, opacity: 0.4 },
]

// hashTilt derives a small, stable tilt from the card's identity so each new top
// card lands at its own angle and the pile looks handled rather than machine
// stacked. Deterministic: the same card always lands the same way.
function hashTilt(card: CardDTO): number {
  const s = cardKey(card)
  let h = 0
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0
  return ((Math.abs(h) % 11) - 5) * 0.9 // −4.5°..+4.5°
}

// Top of the discard pile + active-color ring + pending-draw +N badge.
export function DiscardPile({ card, activeColor, pendingDraw, width, height, topReserve = 0 }: Props) {
  const assist = useColorAssist()
  // The pile reveals on impact, not on the message: the card is still crossing
  // the table, and showing the answer early makes the flight look decorative.
  // The one exception is the first card this pile ever shows (an opening
  // discard, or a board rebuilt after a reconnect), where nothing flew, and
  // waiting for a flight that never happened just blanks the pile.
  const [shown, setShown] = useState<CardDTO | null>(card)
  const isFirst = useRef(true)
  const key = card ? cardKey(card) : ''
  useEffect(() => {
    if (!card) { setShown(null); return }
    if (isFirst.current) {
      isFirst.current = false
      setShown(card)
      return
    }
    const timer = window.setTimeout(() => setShown(card), flightFor(card).duration)
    return () => clearTimeout(timer)
    // Keyed on the card's identity: a re-render must not restage the reveal.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key])

  if (!shown) return null
  const { x, y } = discardPosition(width, height, topReserve)
  const tilt = hashTilt(shown)

  return (
    <div className={styles.pile} style={{ left: x, top: y, width: CARD_W, height: CARD_H }} aria-label="discard">
      {/* Three readings of the same fact, at three distances. The pool is the
          one a spectator gets at 720p without looking for anything; the ring is
          the one a player already knows; the chip is the one that answers the
          question when the card itself cannot — a wild has no colour on its
          face, and that is exactly when people ask where the colour is.
          Keyed on the colour so a wild resolving replays all three. */}
      <motion.div
        key={`pool-${activeColor}`}
        className={styles.pool}
        style={{ color: ACTIVE_RING[activeColor] }}
        initial={{ opacity: 0.78, scale: 1.28 }}
        animate={{ opacity: 0.44, scale: 1 }}
        transition={{ duration: 0.55, ease: 'easeOut' }}
      />
      {/* `color` drives both the border (border-color defaults to currentColor)
          and the glow, so the active colour is set in one place. */}
      <div className={styles.ring} style={{ color: ACTIVE_RING[activeColor] }} />
      {UNDER_LAYERS.map((l, i) => (
        <div
          key={i}
          className={styles.under}
          style={{ transform: `translate(${l.dx}px, ${l.dy}px) rotate(${l.rotate}deg)`, opacity: l.opacity }}
        />
      ))}
      {/* Keyed on the card so every new top card remounts and replays the settle. */}
      <motion.div
        key={cardKey(shown)}
        className={styles.top}
        initial={{ scale: 1.14, rotate: tilt * 2.2, opacity: 0.85 }}
        animate={{ scale: 1, rotate: tilt, opacity: 1 }}
        transition={{ type: 'spring', stiffness: 460, damping: 26, mass: 0.8 }}
      >
        <Card card={shown} />
      </motion.div>
      {/* The chip carries the suit's whole gradient, so it is literally the
          paint of the swatch that was tapped in <ColorPicker /> and of the
          cards it now lets you play. A flat sample would be a fourth colour to
          learn. Bottom-left mirrors the +N badge's corner: the pile has two
          fixed places to look, and this one is always occupied. */}
      <motion.div
        key={`chip-${activeColor}`}
        className={styles.chip}
        style={{
          left: -16,
          top: CARD_H - 22,
          color: ACTIVE_RING[activeColor],
          background: `linear-gradient(${SUIT_ANGLE_DEG}deg, ${SUIT_PAINT[activeColor].from}, ${SUIT_PAINT[activeColor].to})`,
        }}
        aria-label={`active color ${activeColor}`}
        initial={{ scale: 0.35, rotate: -22 }}
        animate={{ scale: 1, rotate: 0 }}
        transition={{ type: 'spring', stiffness: 520, damping: 18 }}
      >
        {/* The chip is the answer to "what can I play now?", and after a wild
            it is the *only* place that answer is written. */}
        {assist && <SuitMark color={activeColor} className={styles.chipMark} />}
      </motion.div>
      {pendingDraw > 0 && (
        <motion.div
          className={styles.badge}
          style={{ left: CARD_W - 46 / 2, top: -30 / 2 }}
          aria-label={`pending draw ${pendingDraw}`}
          initial={{ scale: 0.5, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          transition={{ type: 'spring', stiffness: 600, damping: 22 }}
        >
          +{pendingDraw}
        </motion.div>
      )}
    </div>
  )
}

// client/src/components/cards/DiscardPile.svelte
<script lang="ts">
  import type { CardDTO, CardColor } from '../../types/protocol'
  import Card from './Card.svelte'
  import {
    ACTIVE_RING,
    SUIT_PAINT,
    SUIT_ANGLE_DEG,
    CARD_W,
    CARD_H,
    cardKey,
    flightFor,
  } from './cardTheme'
  import SuitMark from './SuitMark.svelte'
  import { colorAssistPref } from '../../hooks/colorAssist'
  import { watchPref } from '../../hooks/prefs.svelte'
  import { discardPosition } from './layout'

  type Props = {
    card: CardDTO | null
    activeColor: CardColor
    pendingDraw: number
    width: number
    height: number
    /** Vertical space claimed by the opponent seats — the piles follow the felt. */
    topReserve?: number
  }

  let { card, activeColor, pendingDraw, width, height, topReserve = 0 }: Props = $props()

  const assist = watchPref(colorAssistPref)

  // Fixed tilts for the cards buried under the top one. Static rather than random
  // so the pile doesn't reshuffle itself on every update.
  const UNDER_LAYERS = [
    { rotate: -4, dx: -2, dy: 1, opacity: 0.28 },
    { rotate: 3, dx: 1, dy: -1, opacity: 0.4 },
  ]

  // Derives a small, stable tilt from the card's identity so each new top card
  // lands at its own angle and the pile looks handled rather than machine stacked.
  // Deterministic: the same card always lands the same way.
  function hashTilt(c: CardDTO): number {
    const s = cardKey(c)
    let h = 0
    for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0
    return ((Math.abs(h) % 11) - 5) * 0.9 // −4.5°..+4.5°
  }

  // The pile reveals on impact, not on the message: the card is still crossing the
  // table, and showing the answer early makes the flight look decorative. The one
  // exception is the first card this pile ever shows (an opening discard, or a
  // board rebuilt after a reconnect), where nothing flew, and waiting for a flight
  // that never happened just blanks the pile.
  let shown = $state<CardDTO | null>(card)
  let isFirst = true
  const key = $derived(card ? cardKey(card) : '')

  $effect(() => {
    // Read the identity, not the object: a re-render must not restage the reveal.
    key
    const next = card
    if (!next) {
      shown = null
      return
    }
    if (isFirst) {
      isFirst = false
      shown = next
      return
    }
    const timer = window.setTimeout(() => (shown = next), flightFor(next).duration)
    return () => clearTimeout(timer)
  })

  const pos = $derived(discardPosition(width, height, topReserve))
  const tilt = $derived(shown ? hashTilt(shown) : 0)
</script>

<!-- Top of the discard pile + active-colour ring + pending-draw +N badge. -->
{#if shown}
  <div
    class="pile"
    style="left: {pos.x}px; top: {pos.y}px; width: {CARD_W}px; height: {CARD_H}px"
    aria-label="discard"
  >
    <!-- Three readings of the same fact, at three distances. The pool is the one a
         spectator gets at 720p without looking for anything; the ring is the one a
         player already knows; the chip is the one that answers the question when
         the card itself cannot — a wild has no colour on its face, and that is
         exactly when people ask where the colour is. Keyed on the colour so a wild
         resolving replays all three. Framer Motion staged these; they are CSS
         entrance animations now, replayed by the same key. -->
    {#key activeColor}
      <div class="pool" style="color: {ACTIVE_RING[activeColor]}"></div>
    {/key}
    <!-- `color` drives both the border (border-color defaults to currentColor) and
         the glow, so the active colour is set in one place. -->
    <div class="ring" style="color: {ACTIVE_RING[activeColor]}"></div>
    {#each UNDER_LAYERS as l, i (i)}
      <div
        class="under"
        style="transform: translate({l.dx}px, {l.dy}px) rotate({l.rotate}deg); opacity: {l.opacity}"
      ></div>
    {/each}
    <!-- Keyed on the card so every new top card remounts and replays the settle. -->
    {#key cardKey(shown)}
      <div class="top" style="--tilt: {tilt}deg">
        <Card card={shown} />
      </div>
    {/key}
    <!-- The chip carries the suit's whole gradient, so it is literally the paint of
         the swatch that was tapped in <ColorPicker /> and of the cards it now lets
         you play. A flat sample would be a fourth colour to learn. Bottom-left
         mirrors the +N badge's corner: the pile has two fixed places to look, and
         this one is always occupied. -->
    {#key activeColor}
      <div
        class="chip"
        style="left: -16px; top: {CARD_H - 22}px; color: {ACTIVE_RING[
          activeColor
        ]}; background: linear-gradient({SUIT_ANGLE_DEG}deg, {SUIT_PAINT[activeColor]
          .from}, {SUIT_PAINT[activeColor].to})"
        aria-label="active color {activeColor}"
      >
        <!-- The chip is the answer to "what can I play now?", and after a wild it
             is the *only* place that answer is written. -->
        {#if assist.current}<SuitMark color={activeColor} class="chipMark" />{/if}
      </div>
    {/key}
    {#if pendingDraw > 0}
      <div
        class="badge"
        style="left: {CARD_W - 46 / 2}px; top: {-30 / 2}px"
        aria-label="pending draw {pendingDraw}"
      >
        +{pendingDraw}
      </div>
    {/if}
  </div>
{/if}

<style>
  .pile {
    position: absolute;
    pointer-events: none;
  }

  /* Coloured light pooled on the felt around the discard. The ring states the
     active colour precisely; this one states it from across the room — a viewer on
     a 720p stream reads a red table before they read a red outline, and a player
     who just looked away reads it without hunting.
     Deliberately low and blurred: the table stays near-black and the card edges
     keep winning, which is the rule the felt exists to protect. Centred with
     margins, not `transform` — the entrance animation owns this node's transform. */
  .pool {
    position: absolute;
    left: 50%;
    top: 50%;
    width: 330px;
    height: 286px;
    margin-left: -165px;
    margin-top: -143px;
    border-radius: 50%;
    background: radial-gradient(closest-side, currentColor 0%, rgba(0, 0, 0, 0) 72%);
    filter: blur(18px);
    pointer-events: none;
    animation: poolIn 0.55s var(--ease-out) both;
  }

  @keyframes poolIn {
    from {
      opacity: 0.78;
      transform: scale(1.28);
    }
    to {
      opacity: 0.44;
      transform: scale(1);
    }
  }

  /* Active-colour halo. This is the single most-consulted piece of state on the
     board, so it is a solid glowing ring rather than a hairline: readable from a
     stream thumbnail, and it changes the moment a wild resolves. */
  .ring {
    position: absolute;
    top: -11px;
    left: -11px;
    width: calc(72px + 22px);
    height: calc(108px + 22px);
    border-radius: 20px;
    border-width: 5px;
    border-style: solid;
    box-shadow:
      0 0 22px 3px currentColor,
      inset 0 0 12px rgba(255, 255, 255, 0.35);
    opacity: 0.95;
    pointer-events: none;
    animation: ringBreathe 2.6s ease-in-out infinite;
  }

  @keyframes ringBreathe {
    0%,
    100% {
      opacity: 0.95;
    }
    50% {
      opacity: 0.7;
    }
  }

  /* Buried cards giving the pile visible thickness. Deliberately neutral: the
     active-colour ring already owns the colour around the discard, and tinted
     layers underneath would muddy it. */
  .under {
    position: absolute;
    top: 0;
    left: 0;
    width: 72px;
    height: 108px;
    border-radius: 11px;
    background: #fff;
    border: var(--stroke-thin) solid var(--color-stroke);
    transform-origin: 50% 50%;
    pointer-events: none;
  }

  /* The settle: the card lands a touch large and over-tilted, then sits. */
  .top {
    position: absolute;
    top: 0;
    left: 0;
    transform-origin: 50% 50%;
    will-change: transform;
    animation: topSettle 0.42s var(--ease-bounce) both;
  }

  @keyframes topSettle {
    from {
      opacity: 0.85;
      transform: scale(1.14) rotate(calc(var(--tilt) * 2.2));
    }
    to {
      opacity: 1;
      transform: scale(1) rotate(var(--tilt));
    }
  }

  /* Stacked penalty counter. Sits on the card's corner like a damage number. */
  .badge {
    position: absolute;
    width: 46px;
    height: 30px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: linear-gradient(180deg, #ff6d7d 0%, var(--color-primary) 100%);
    border: var(--stroke) solid var(--color-stroke);
    border-radius: var(--radius-full);
    color: var(--color-on-primary);
    font: 700 16px/1 var(--font-display);
    pointer-events: none;
    z-index: 2;
    box-shadow:
      0 3px 0 var(--color-stroke-soft),
      0 0 18px rgba(255, 61, 104, 0.6);
    animation: badgePop 0.32s var(--ease-bounce) both;
  }

  @keyframes badgePop {
    from {
      opacity: 0;
      transform: scale(0.5);
    }
    to {
      opacity: 1;
      transform: scale(1);
    }
  }

  /* The active-colour chip: a physical token set into the ring, in the app's
     chunky language (ink outline + hard ledge) because it is an object on the
     table, not a swatch in a legend. Same corner discipline as .badge. */
  .chip {
    position: absolute;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 38px;
    height: 38px;
    border-radius: var(--radius-full);
    border: var(--stroke) solid var(--color-stroke);
    box-shadow:
      0 3px 0 var(--color-stroke-soft),
      0 0 16px currentColor,
      inset 0 2px 4px rgba(255, 255, 255, 0.4);
    pointer-events: none;
    z-index: 3;
    animation: chipPop 0.36s var(--ease-bounce) both;
  }

  @keyframes chipPop {
    from {
      transform: scale(0.35) rotate(-22deg);
    }
    to {
      transform: scale(1) rotate(0deg);
    }
  }

  /* Colour assist: the suit silhouette inside the active-colour chip. Global
     because <SuitMark /> renders the element. */
  .chip :global(.chipMark) {
    width: 58%;
    height: 58%;
  }

  :root[data-motion="reduce"] .ring {
    animation: none;
  }

  /* The entrances degrade to their end state, never to nothing: the pile, the
     colour and the penalty are all information. */
  :root[data-motion="reduce"] .pool,
  :root[data-motion="reduce"] .top,
  :root[data-motion="reduce"] .chip,
  :root[data-motion="reduce"] .badge {
    animation-duration: 0.01ms;
  }
</style>
