// client/src/components/cards/Hand.tsx
import { useEffect, useRef, useState } from 'react'
import { motion } from 'framer-motion'
import { CardDTO, CardColor } from '../../types/protocol'
import { Card } from './Card'
import { calcHandSlots, handCardKeys } from './layout'
import { CARD_W, CARD_H, SPRING_HAND, DEAL_STAGGER_MS, radToDeg } from './cardTheme'
import styles from './Hand.module.css'

interface Props {
  hand: CardDTO[]
  width: number
  height: number
  /** Predicate run per card to decide playable/highlight state. */
  isPlayable: (card: CardDTO) => boolean
  /** Predicate that decides whether a tap should be allowed at all (turn or
      legal interrupt). When false, the card renders without pointer cursor. */
  isInteractive: (card: CardDTO) => boolean
  onCardClick: (card: CardDTO, idx: number) => void
}

// Hand renders the local player's fanned cards. Pure presentational —
// position / rotation comes from `calcHandSlots`. Hover state is local.
//
// Each slot is a motion node positioned purely by transform, so when a card
// leaves the fan the neighbours glide into the gap on a spring instead of
// snapping to their new left/top. A fresh deal staggers the cards in.
export function Hand({
  hand,
  width,
  height,
  isPlayable,
  isInteractive,
  onCardClick,
}: Props) {
  const [hoveredIdx, setHoveredIdx] = useState<number | null>(null)

  // A hand that grows from empty is a deal — worth staggering. Any other growth
  // is a draw, which already has its own deck→hand flier and must not stagger.
  const prevLen = useRef(hand.length)
  const [dealing, setDealing] = useState(false)
  useEffect(() => {
    const wasEmpty = prevLen.current === 0
    prevLen.current = hand.length
    if (!wasEmpty || hand.length < 2) return
    setDealing(true)
    const id = setTimeout(() => setDealing(false), hand.length * DEAL_STAGGER_MS + 400)
    return () => clearTimeout(id)
  }, [hand.length])

  if (hand.length === 0) return null
  const slots = calcHandSlots(hand.length, width, height)
  const keys = handCardKeys(hand)

  return (
    <div className={styles.hand} aria-label="hand">
      {hand.map((card, i) => {
        const slot = slots[i]
        const playable = isPlayable(card)
        const interactive = isInteractive(card)
        // Playable cards lift slightly even at rest so they stand out.
        const restLift = playable ? -9 : 0
        const isHovered = hoveredIdx === i
        return (
          <motion.div
            key={keys[i]}
            className={`${styles.slot}${isHovered ? ' ' + styles.hovered : ''}`}
            style={{ width: CARD_W, height: CARD_H, zIndex: isHovered ? 100 : i }}
            initial={{ x: slot.x, y: slot.y + restLift, rotate: radToDeg(slot.rotation), opacity: 0, scale: 0.88 }}
            animate={{
              x: slot.x,
              y: slot.y + restLift,
              // Hovering straightens the card so its face is fully readable.
              rotate: isHovered ? 0 : radToDeg(slot.rotation),
              opacity: 1,
              scale: 1,
            }}
            transition={{
              ...SPRING_HAND,
              delay: dealing ? (i * DEAL_STAGGER_MS) / 1000 : 0,
            }}
            onMouseEnter={() => setHoveredIdx(i)}
            onMouseLeave={() => setHoveredIdx((cur) => (cur === i ? null : cur))}
          >
            <Card
              card={card}
              playable={playable}
              shadow
              onClick={interactive ? () => onCardClick(card, i) : undefined}
              className={styles.card}
            />
          </motion.div>
        )
      })}
    </div>
  )
}

// Re-export for places that need the same predicate without importing the
// helper directly (avoids a cycle through GameView).
export type HandPlayablePredicate = (card: CardDTO, top: CardDTO | null, active: CardColor) => boolean

// client/src/components/cards/Hand.svelte
<script lang="ts">
  import type { CardDTO } from '../../types/protocol'
  import Card from './Card.svelte'
  import { calcHandSlots, handCardKeys } from './layout'
  import { CARD_W, CARD_H, DEAL_STAGGER_MS, radToDeg } from './cardTheme'

  type Props = {
    hand: CardDTO[]
    width: number
    height: number
    /** Predicate run per card to decide playable/highlight state. */
    isPlayable: (card: CardDTO) => boolean
    /**
     * Predicate that decides whether a tap should be allowed at all (turn or legal
     * interrupt). When false, the card renders without pointer cursor.
     */
    isInteractive: (card: CardDTO) => boolean
    onCardClick: (card: CardDTO, idx: number) => void
  }

  let { hand, width, height, isPlayable, isInteractive, onCardClick }: Props = $props()

  let hoveredIdx = $state<number | null>(null)

  // A hand that grows from empty is a deal — worth staggering. Any other growth is
  // a draw, which already has its own deck→hand flier and must not stagger.
  let prevLen = 0
  let dealing = $state(false)
  $effect(() => {
    const len = hand.length
    const wasEmpty = prevLen === 0
    prevLen = len
    if (!wasEmpty || len < 2) return
    dealing = true
    const id = setTimeout(() => (dealing = false), len * DEAL_STAGGER_MS + 400)
    return () => clearTimeout(id)
  })

  const slots = $derived(calcHandSlots(hand.length, width, height))
  const keys = $derived(handCardKeys(hand))
</script>

<!--
  The local player's fanned cards. Pure presentational — position and rotation come
  from `calcHandSlots`, hover state is local.

  Each slot is positioned purely by transform, so when a card leaves the fan the
  neighbours glide into the gap instead of snapping to their new left/top. Framer
  Motion ran that on a spring per card; it is a CSS transition now, which keeps the
  reflow on the compositor and off the main thread — the thing that matters most on
  a board whose whole point is answering a tap instantly. A fresh deal staggers the
  cards in through a per-card delay.
-->
{#if hand.length > 0}
  <div class="hand" aria-label="hand">
    {#each hand as card, i (keys[i])}
      {@const slot = slots[i]}
      {@const playable = isPlayable(card)}
      {@const interactive = isInteractive(card)}
      <!-- Playable cards lift slightly even at rest so they stand out. -->
      {@const restLift = playable ? -9 : 0}
      {@const hovered = hoveredIdx === i}
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div
        class="slot"
        class:hovered
        class:dealing
        style="width: {CARD_W}px; height: {CARD_H}px; z-index: {hovered
          ? 100
          : i}; transform: translate({slot.x}px, {slot.y + restLift}px) rotate({hovered
          ? 0
          : radToDeg(slot.rotation)}deg); transition-delay: {dealing
          ? i * DEAL_STAGGER_MS
          : 0}ms; animation-delay: {dealing ? i * DEAL_STAGGER_MS : 0}ms"
        onmouseenter={() => (hoveredIdx = i)}
        onmouseleave={() => {
          if (hoveredIdx === i) hoveredIdx = null
        }}
      >
        <Card
          {card}
          {playable}
          shadow
          onclick={interactive ? () => onCardClick(card, i) : undefined}
          class="card"
        />
      </div>
    {/each}
  </div>
{/if}

<style>
  .hand {
    position: absolute;
    inset: 0;
    pointer-events: none;
  }

  .slot {
    position: absolute;
    /* Pinned at the origin: placement and rotation are the inline transform, so
       nothing here may set left/top/transform or it would fight the reflow. */
    left: 0;
    top: 0;
    pointer-events: auto;
    transform-origin: 50% 50%;
    will-change: transform;
    /* The fan re-spreads when a card leaves and straightens under the pointer.
       Cubic-bezier rather than a spring: the overshoot a spring gave was never
       readable at this size, and this costs no frame budget at all. */
    transition: transform 420ms cubic-bezier(0.22, 1, 0.28, 1);
    animation: handCardIn 380ms cubic-bezier(0.22, 1, 0.28, 1) both;
  }

  @keyframes handCardIn {
    from {
      opacity: 0;
    }
    to {
      opacity: 1;
    }
  }

  /* The lift lives on the inner card so the slot's transform stays exclusively the
     fan's — two nested transforms, no conflict. Global because <Card /> renders
     the element that wears it. */
  .slot :global(.card) {
    transform-origin: 50% 50%;
    transition:
      transform 180ms cubic-bezier(0.16, 1, 0.3, 1),
      box-shadow 180ms cubic-bezier(0.16, 1, 0.3, 1);
  }

  .slot.hovered :global(.card) {
    transform: scale(1.08) translateY(-14px);
  }

  :root[data-motion="reduce"] .slot {
    transition: none;
    animation: none;
  }

  :root[data-motion="reduce"] .slot :global(.card) {
    transition: none;
  }
</style>
