// client/src/components/Lobby.svelte
<script lang="ts">
  import type { ClientMsg } from '../types/protocol'
  import { i18n } from '../i18n/i18n.svelte'
  import { resolveServerError } from '../i18n/serverErrors'
  import RulesButton from './RulesButton.svelte'
  import RulesModal from './RulesModal.svelte'
  import Preferences from './Preferences.svelte'
  import AudioSettings from './AudioSettings.svelte'
  import LocoLogo from './LocoLogo.svelte'
  import { playSfx } from '../audio/sfx'
  import { readNickname, rememberNickname } from '../hooks/nicknameMemory'
  import { canonicalNickname, isNicknameShapeValid } from './nicknameRules'
  import { TABLE_CODE_LENGTH, isTableCodeValid, sanitizeTableCode } from './tableCodeRules'

  type LobbyMode = 'home' | 'find' | 'create' | 'join'

  type Props = {
    onSend: (msg: ClientMsg) => void
    /**
     * Enters the 1v1 queue. Separate from onSend because the search screen is
     * entered optimistically, before the server has acknowledged anything.
     */
    onFindMatch: (nickname: string) => void
    error: string
    onClearError: () => void
    /**
     * Starting sub-screen. Set by the visual showcase, and by a table link, which
     * opens straight on the join form.
     */
    initialMode?: LobbyMode
    /**
     * The table code a shared link arrived with. A prefill for the field, not a
     * submission: the form still refuses to send without a nickname, and the
     * server still owns the verdict on the code.
     */
    initialCode?: string
    /** Showcase only: mounts with the preferences panel open. */
    initialPrefsOpen?: boolean
  }

  let {
    onSend,
    onFindMatch,
    error,
    onClearError,
    initialMode = 'home',
    initialCode = '',
    initialPrefsOpen = false,
  }: Props = $props()

  const t = $derived(i18n.t)

  // Read once, at setup: the field is the player's from then on, and re-reading
  // storage would fight whatever they are typing.
  let nickname = $state(readNickname())
  // Read once, like the nickname: from here on the field belongs to the player,
  // and a link that has been spent must not put its code back.
  let roomCode = $state(sanitizeTableCode(initialCode))
  let mode = $state<LobbyMode>(initialMode)
  let showRules = $state(false)
  // The shape rules the client can check itself, answered as the player types
  // rather than after a round trip. It says nothing the server would not have
  // said: the same one line, for the same reason (server/game/nickname.go).
  let nicknameRefused = $state(false)

  function editNickname(value: string) {
    nickname = value
    nicknameRefused = value.trim() !== '' && !isNicknameShapeValid(value)
    onClearError()
  }

  /** Guards every entry point. Returns the form to send, or '' to refuse. */
  function acceptNickname(): string {
    if (!isNicknameShapeValid(nickname)) {
      nicknameRefused = nickname.trim() !== ''
      return ''
    }
    const value = canonicalNickname(nickname)
    rememberNickname(value)
    return value
  }

  // Leaving a sub-screen gets the descending blip; entering one is silent because
  // the screen change is already obvious.
  function goHome() {
    playSfx('uiBack')
    mode = 'home'
  }

  function handleFind(e: SubmitEvent) {
    e.preventDefault()
    const value = acceptNickname()
    if (!value) return
    onFindMatch(value)
  }

  function handleCreate(e: SubmitEvent) {
    e.preventDefault()
    const value = acceptNickname()
    if (!value) return
    onSend({ type: 'create_room', nickname: value })
  }

  function handleJoin(e: SubmitEvent) {
    e.preventDefault()
    const value = acceptNickname()
    if (!value || !isTableCodeValid(roomCode)) return
    onSend({ type: 'join_room', nickname: value, room_code: sanitizeTableCode(roomCode) })
  }
</script>

<div class="container">
  <div class="topBar">
    <!-- The one screen where the gear stands down on a phone: this is the only
         screen the home page's burger is on, and its drawer carries a Preferences
         row already. Everywhere past a taken seat that drawer is gone with the
         footer, so the chip stays at every width there. -->
    <Preferences defaultOpen={initialPrefsOpen} triggerBelowPhone={false} />
    <AudioSettings />
    <RulesButton label={t.rulesBtn} onclick={() => (showRules = true)} />
  </div>

  <!-- The mark, not the page's heading. `GamePage.astro` serves the one top-level
       heading this document has, in text, before any of this mounts; wrapping a
       logotype in a second one gave `/` two headings that both said "LOCO" and
       neither of which said what the page was. -->
  <div class="title">
    <LocoLogo size="clamp(58px, 11vw, 128px)" animated />
  </div>
  <p class="tagline">{t.tagline}</p>

  <!-- An alert, not a control: it announces itself to assistive tech and clears
       as soon as the player edits the field it is complaining about, so it never
       needed to be clickable to be dismissible. Styling it as a filled pill the
       same size as the CTA below made it read as a third button on the screen. -->
  {#if nicknameRefused || error}
    <p class="error" role="alert">
      {nicknameRefused ? t.errors.nicknameRejected : resolveServerError(error, t.errors)}
    </p>
  {/if}

  {#if mode === 'home'}
    <div class="buttonGroup">
      <!-- One player, one button, one opponent. It leads because it is the only
           entry point that needs nobody else to be organised, and it carries the
           game's hue for that reason. The two table buttons underneath stay
           equally weighted between themselves: neither of them is a fallback for
           the other. -->
      <button class="btn" onclick={() => (mode = 'find')}>
        {t.findMatch}
        <span class="btnHint">{t.findMatchHint}</span>
      </button>
      <button class="btn btnAlt" onclick={() => (mode = 'create')}>{t.createRoom}</button>
      <button class="btn btnJoin" onclick={() => (mode = 'join')}>{t.joinRoom}</button>
    </div>
  {/if}

  {#if mode === 'find'}
    <form class="form" onsubmit={handleFind}>
      <!-- svelte-ignore a11y_autofocus -->
      <input
        class="input"
        placeholder={t.yourNickname}
        value={nickname}
        oninput={(e) => editNickname(e.currentTarget.value)}
        maxlength="20"
        autofocus
      />
      <button class="btn" type="submit">{t.findMatchGo}</button>
      <button class="btnSecondary" type="button" onclick={goHome}>{t.back}</button>
    </form>
  {/if}

  {#if mode === 'create'}
    <form class="form" onsubmit={handleCreate}>
      <!-- svelte-ignore a11y_autofocus -->
      <input
        class="input"
        placeholder={t.yourNickname}
        value={nickname}
        oninput={(e) => editNickname(e.currentTarget.value)}
        maxlength="20"
        autofocus
      />
      <button class="btn" type="submit">{t.createGame}</button>
      <button class="btnSecondary" type="button" onclick={goHome}>{t.back}</button>
    </form>
  {/if}

  {#if mode === 'join'}
    <form class="form" onsubmit={handleJoin}>
      <!-- A returning player already has a name in the field, so the caret
           belongs on the one thing they still have to type. -->
      <!-- svelte-ignore a11y_autofocus -->
      <input
        class="input"
        placeholder={t.yourNickname}
        value={nickname}
        oninput={(e) => editNickname(e.currentTarget.value)}
        maxlength="20"
        autofocus={!nickname}
      />
      <!-- The field only ever holds a possible code: the alphabet is the server's
           (tableCodeRules.ts), and anything else is dropped as it is typed or
           pasted rather than kept for the server to refuse. -->
      <!-- svelte-ignore a11y_autofocus -->
      <input
        class="input"
        placeholder={t.roomCodeLabel}
        value={roomCode}
        oninput={(e) => {
          roomCode = sanitizeTableCode(e.currentTarget.value)
          e.currentTarget.value = roomCode
          onClearError()
        }}
        maxlength={TABLE_CODE_LENGTH}
        autofocus={!!nickname && !roomCode}
        inputmode="text"
        autocapitalize="characters"
        autocorrect="off"
        spellcheck="false"
      />
      <!-- Nothing to take a seat at until the code is whole. The button says so
           instead of sending a request whose only outcome is an error line under a
           form the player has not finished filling in. -->
      <button class="btn" type="submit" disabled={!isTableCodeValid(roomCode)}>
        {t.joinGame}
      </button>
      <button class="btnSecondary" type="button" onclick={goHome}>{t.back}</button>
    </form>
  {/if}

  <!-- Privacy and terms are not here any more: they are a page, linked at the
       right-hand end of the footer this screen sits above (GamePage.astro). A
       policy has to be linkable, and the entry screen is the one screen that
       footer is visible on anyway. -->

  {#if showRules}
    <RulesModal onClose={() => (showRules = false)} />
  {/if}
</div>

<style>
  /* Entry screen. First impression of the game, so the logo is a physical object
     with depth and the two CTAs are unmistakably pressable. */

  .container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    /* `safe` keeps overflowing content anchored to the top instead of centring it
       out of the scroll area, where the first rows become unreachable. */
    justify-content: safe center;
    height: 100%;
    overflow-y: auto;
    padding: calc(var(--space-lg) + var(--safe-top)) calc(var(--space-base) + var(--safe-right))
      calc(var(--space-lg) + var(--safe-bottom)) calc(var(--space-base) + var(--safe-left));
    gap: var(--space-lg);
    position: relative;
    background: transparent;
    color: var(--color-ink);
    font-family: var(--font-body);
  }

  .topBar {
    position: absolute;
    top: calc(var(--space-base) + var(--safe-top));
    right: calc(var(--space-base) + var(--safe-right));
    display: flex;
    align-items: center;
    gap: var(--space-sm);
  }

  /* The rules opener is <RulesButton />, which carries its own chip styling. */

  /* The wordmark and its treatment live in <LocoLogo />, which the waiting room
     and the game-over card share. All this owns is the space around it. */
  .title {
    margin-bottom: -2px;
  }

  /* The tagline belongs to the wordmark, not to the buttons. At the container's
     own gap it sat equidistant from both and read as a third floating object;
     pulling it up binds the pair into one lockup and leaves a clear step down to
     the controls. */
  .tagline {
    margin-top: -10px;
    color: var(--color-body);
    font: 700 13px/1.3 var(--font-display);
    letter-spacing: 0.14em;
    text-transform: uppercase;
    padding: 7px 16px;
    background: var(--color-surface-card);
    border: var(--stroke-thin) solid var(--color-stroke);
    border-radius: var(--radius-full);
    box-shadow: 0 3px 0 var(--color-stroke-soft);
  }

  .form {
    display: flex;
    flex-direction: column;
    gap: var(--space-md);
    /* Grows with the room. A fixed 320px column on a 1440px monitor reads as a
       phone layout that was never given a desktop, and it is what left the entry
       screen looking mostly empty. */
    width: clamp(320px, 28vw, 400px);
  }

  .input {
    padding: 14px 18px;
    border-radius: var(--radius-md);
    border: var(--stroke) solid var(--color-stroke);
    background: var(--color-surface-card);
    color: var(--color-ink);
    font: 600 17px/1.4 var(--font-body);
    height: 56px;
    outline: none;
    box-shadow: inset 0 3px 0 rgba(36, 21, 70, 0.08);
    transition: box-shadow 0.15s ease;
  }

  .input:focus {
    box-shadow:
      inset 0 3px 0 rgba(36, 21, 70, 0.08),
      0 0 0 4px rgba(108, 92, 255, 0.35);
  }

  /* The placeholder is the only instruction this field ever gives, so it is held
     at the same contrast as the rest of the quiet copy rather than at the next
     step down. */
  .input::placeholder {
    color: var(--color-muted);
    font-weight: 500;
  }

  .buttonGroup {
    display: flex;
    flex-direction: column;
    gap: var(--space-md);
    /* Same reason as the form above. */
    width: clamp(320px, 28vw, 400px);
  }

  .btn {
    width: 100%;
    padding: 14px 24px;
    min-height: 54px;
    border-radius: var(--radius-full);
    border: var(--stroke) solid var(--color-stroke);
    background: var(--gradient-primary);
    color: var(--color-on-primary);
    text-shadow: 0 2px 0 rgba(120, 10, 40, 0.4);
    font: 700 19px/1.2 var(--font-display);
    cursor: pointer;
    box-shadow: 0 5px 0 var(--color-stroke-soft);
    transition:
      transform 0.12s var(--ease-bounce),
      box-shadow 0.12s var(--ease-out),
      filter 0.12s ease;
    touch-action: manipulation;
  }

  .btn:hover:not(:disabled) {
    transform: translateY(-3px);
    box-shadow: 0 8px 0 var(--color-stroke-soft);
    filter: brightness(1.06);
  }
  .btn:active:not(:disabled) {
    transform: translateY(3px);
    box-shadow: 0 2px 0 var(--color-stroke-soft);
  }

  .btn:disabled {
    background: var(--color-surface-strong);
    color: var(--color-muted);
    cursor: not-allowed;
    box-shadow: none;
    text-shadow: none;
  }

  /* The two table entry points under the 1v1 button: equal weight between
     themselves, each with its own hue so neither reads as the other's fallback.
     Both classes are applied in the markup rather than `composes: btn`, which is
     a CSS Modules directive with no Svelte equivalent. */
  .btnAlt {
    background: var(--gradient-secondary);
    color: var(--color-on-secondary);
    text-shadow: none;
  }

  .btnJoin {
    background: var(--gradient-tertiary);
    text-shadow: 0 2px 0 rgba(30, 16, 90, 0.4);
  }

  /* The 1v1 button carries a second line: "find an opponent" says nothing about
     what a player is signing up for, and "one round against a stranger, right
     now" is the entire pitch of the mode. Stacked inside the button rather than
     set beneath it so the whole promise is the thing being pressed. */
  .btn:has(.btnHint) {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 2px;
    padding-top: 11px;
    padding-bottom: 11px;
  }

  .btnHint {
    font: 600 12px/1.2 var(--font-display);
    letter-spacing: 0.08em;
    text-transform: uppercase;
    opacity: 0.85;
    text-shadow: none;
  }

  /* Back / cancel — deliberately quiet so it never competes with the submit. */
  .btnSecondary {
    width: 100%;
    padding: 12px 24px;
    min-height: 48px;
    border-radius: var(--radius-full);
    border: var(--stroke) solid var(--color-stroke);
    background: var(--color-surface-card);
    color: var(--color-ink);
    font: 600 16px/1.2 var(--font-display);
    cursor: pointer;
    box-shadow: 0 4px 0 var(--color-stroke-soft);
    transition:
      transform 0.12s var(--ease-bounce),
      box-shadow 0.12s var(--ease-out);
    touch-action: manipulation;
  }

  .btnSecondary:hover {
    transform: translateY(-2px);
    box-shadow: 0 6px 0 var(--color-stroke-soft);
  }
  .btnSecondary:active {
    transform: translateY(2px);
    box-shadow: 0 2px 0 var(--color-stroke-soft);
  }

  /* A refusal, not an action. Every pressable object on this screen is a vertical
     gradient with a 5px ledge; the alert is deliberately *flat* with a shallower
     ledge, so it reads as a label stuck on the page rather than as a third button
     between the logo and the CTA. The glyph carries the meaning for anyone who
     cannot rely on the colour alone. */
  .error {
    display: flex;
    align-items: center;
    gap: var(--space-sm);
    margin: 0;
    background: var(--color-error);
    border: var(--stroke-thin) solid var(--color-stroke);
    border-radius: var(--radius-md);
    padding: 10px 18px;
    color: var(--color-on-dark);
    max-width: 340px;
    text-align: left;
    text-wrap: balance;
    font: 600 15px/1.35 var(--font-body);
    box-shadow: 0 3px 0 var(--color-stroke-soft);
    animation: errorShake 0.4s ease-out;
  }

  .error::before {
    content: '!';
    flex: none;
    display: grid;
    place-items: center;
    width: 22px;
    height: 22px;
    border-radius: var(--radius-full);
    background: #fff;
    color: var(--color-error);
    font: 700 15px/1 var(--font-display);
  }

  @keyframes errorShake {
    0%,
    100% {
      transform: translateX(0);
    }
    20% {
      transform: translateX(-7px);
    }
    45% {
      transform: translateX(6px);
    }
    70% {
      transform: translateX(-3px);
    }
  }

  @media (max-width: 480px) {
    .form {
      width: 90vw;
      max-width: 340px;
    }

    .buttonGroup {
      width: 90vw;
      max-width: 340px;
    }
  }

  :root[data-motion="reduce"] .error {
    animation: none;
  }
</style>

// client/src/components/Lobby.tsx
import { useState } from 'react'
// React 19's types deprecate the FormEvent alias (the DOM event a submit fires
// is a SubmitEvent); SyntheticEvent is the base these handlers actually need.
import type { SyntheticEvent } from 'react'
import { ClientMsg } from '../types/protocol'
import { useI18n } from '../i18n'
import { resolveServerError } from '../i18n/serverErrors'
import { RulesButton } from './RulesButton'
import { RulesModal } from './RulesModal'
import { Preferences } from './Preferences'
import { AudioSettings } from './AudioSettings'
import { LocoLogo } from './LocoLogo'
import { playSfx } from '../audio/sfx'
import { readNickname, rememberNickname } from '../hooks/nicknameMemory'
import { canonicalNickname, isNicknameShapeValid } from './nicknameRules'
import { TABLE_CODE_LENGTH, isTableCodeValid, sanitizeTableCode } from './tableCodeRules'
import styles from './Lobby.module.css'

type LobbyMode = 'home' | 'find' | 'create' | 'join'

interface Props {
  onSend: (msg: ClientMsg) => void
  /** Enters the 1v1 queue. Separate from onSend because the search screen is
   *  entered optimistically, before the server has acknowledged anything. */
  onFindMatch: (nickname: string) => void
  error: string
  onClearError: () => void
  /** Starting sub-screen. Set by the visual showcase, and by a table link,
   *  which opens straight on the join form. */
  initialMode?: LobbyMode
  /** The table code a shared link arrived with. A prefill for the field, not a
   *  submission: the form still refuses to send without a nickname, and the
   *  server still owns the verdict on the code. */
  initialCode?: string
  /** Showcase only: mounts with the preferences panel open. */
  initialPrefsOpen?: boolean
}

export function Lobby({
  onSend,
  onFindMatch,
  error,
  onClearError,
  initialMode = 'home',
  initialCode = '',
  initialPrefsOpen = false,
}: Props) {
  const { t } = useI18n()
  // Read once, at mount: the field is the player's from then on, and re-reading
  // storage would fight whatever they are typing.
  const [nickname, setNickname] = useState(readNickname)
  // Read once, like the nickname: from here on the field belongs to the player,
  // and a link that has been spent must not put its code back.
  const [roomCode, setRoomCode] = useState(() => sanitizeTableCode(initialCode))
  const [mode, setMode] = useState<LobbyMode>(initialMode)
  const [showRules, setShowRules] = useState(false)
  // The shape rules the client can check itself, answered as the player types
  // rather than after a round trip. It says nothing the server would not have
  // said: the same one line, for the same reason (server/game/nickname.go).
  const [nicknameRefused, setNicknameRefused] = useState(false)

  const editNickname = (value: string) => {
    setNickname(value)
    setNicknameRefused(value.trim() !== '' && !isNicknameShapeValid(value))
    onClearError()
  }

  /** Guards every entry point. Returns the form to send, or '' to refuse. */
  const acceptNickname = (): string => {
    if (!isNicknameShapeValid(nickname)) {
      setNicknameRefused(nickname.trim() !== '')
      return ''
    }
    const value = canonicalNickname(nickname)
    rememberNickname(value)
    return value
  }

  // Leaving a sub-screen gets the descending blip; entering one is silent
  // because the screen change is already obvious.
  const goHome = () => {
    playSfx('uiBack')
    setMode('home')
  }

  const handleFind = (e: SyntheticEvent) => {
    e.preventDefault()
    const value = acceptNickname()
    if (!value) return
    onFindMatch(value)
  }

  const handleCreate = (e: SyntheticEvent) => {
    e.preventDefault()
    const value = acceptNickname()
    if (!value) return
    onSend({ type: 'create_room', nickname: value })
  }

  const handleJoin = (e: SyntheticEvent) => {
    e.preventDefault()
    const value = acceptNickname()
    if (!value || !isTableCodeValid(roomCode)) return
    onSend({ type: 'join_room', nickname: value, room_code: sanitizeTableCode(roomCode) })
  }

  return (
    <div className={styles.container}>
      <div className={styles.topBar}>
        {/* The one screen where the gear stands down on a phone: this is the
            only screen the home page's burger is on, and its drawer carries a
            Preferences row already. Everywhere past a taken seat that drawer is
            gone with the footer, so the chip stays at every width there. */}
        <Preferences defaultOpen={initialPrefsOpen} triggerBelowPhone={false} />
        <AudioSettings />
        <RulesButton label={t.rulesBtn} onClick={() => setShowRules(true)} />
      </div>

      {/* The mark, not the page's heading. `GamePage.astro` serves the one
          top-level heading this document has, in text, before any of this
          mounts; wrapping a logotype in a second one gave `/` two headings that
          both said "LOCO" and neither of which said what the page was. */}
      <div className={styles.title}>
        <LocoLogo size="clamp(58px, 11vw, 128px)" animated />
      </div>
      <p className={styles.tagline}>{t.tagline}</p>

      {/* An alert, not a control: it announces itself to assistive tech and
          clears as soon as the player edits the field it is complaining about,
          so it never needed to be clickable to be dismissible. Styling it as a
          filled pill the same size as the CTA below made it read as a third
          button on the screen. */}
      {(nicknameRefused || error) && (
        <p className={styles.error} role="alert">
          {nicknameRefused ? t.errors.nicknameRejected : resolveServerError(error, t.errors)}
        </p>
      )}

      {mode === 'home' && (
        <div className={styles.buttonGroup}>
          {/* One player, one button, one opponent. It leads because it is the
              only entry point that needs nobody else to be organised, and it
              carries the game's hue for that reason. The two table buttons
              underneath stay equally weighted between themselves: neither of
              them is a fallback for the other. */}
          <button className={styles.btn} onClick={() => setMode('find')}>
            {t.findMatch}
            <span className={styles.btnHint}>{t.findMatchHint}</span>
          </button>
          <button className={styles.btnAlt} onClick={() => setMode('create')}>
            {t.createRoom}
          </button>
          <button className={styles.btnJoin} onClick={() => setMode('join')}>
            {t.joinRoom}
          </button>
        </div>
      )}

      {mode === 'find' && (
        <form className={styles.form} onSubmit={handleFind}>
          <input
            className={styles.input}
            placeholder={t.yourNickname}
            value={nickname}
            onChange={(e) => editNickname(e.target.value)}
            maxLength={20}
            autoFocus
          />
          <button className={styles.btn} type="submit">
            {t.findMatchGo}
          </button>
          <button className={styles.btnSecondary} type="button" onClick={goHome}>
            {t.back}
          </button>
        </form>
      )}

      {mode === 'create' && (
        <form className={styles.form} onSubmit={handleCreate}>
          <input
            className={styles.input}
            placeholder={t.yourNickname}
            value={nickname}
            onChange={(e) => editNickname(e.target.value)}
            maxLength={20}
            autoFocus
          />
          <button className={styles.btn} type="submit">
            {t.createGame}
          </button>
          <button className={styles.btnSecondary} type="button" onClick={goHome}>
            {t.back}
          </button>
        </form>
      )}

      {mode === 'join' && (
        <form className={styles.form} onSubmit={handleJoin}>
          <input
            className={styles.input}
            placeholder={t.yourNickname}
            value={nickname}
            onChange={(e) => editNickname(e.target.value)}
            maxLength={20}
            autoFocus={!nickname}
          />
          {/* A returning player already has a name in the field, so the caret
              belongs on the one thing they still have to type. */}
          {/* The field only ever holds a possible code: the alphabet is the
              server's (tableCodeRules.ts), and anything else is dropped as it
              is typed or pasted rather than kept for the server to refuse. */}
          <input
            className={styles.input}
            placeholder={t.roomCodeLabel}
            value={roomCode}
            onChange={(e) => { setRoomCode(sanitizeTableCode(e.target.value)); onClearError() }}
            maxLength={TABLE_CODE_LENGTH}
            autoFocus={!!nickname && !roomCode}
            inputMode="text"
            autoCapitalize="characters"
            autoCorrect="off"
            spellCheck={false}
          />
          {/* Nothing to take a seat at until the code is whole. The button says
              so instead of sending a request whose only outcome is an error
              line under a form the player has not finished filling in. */}
          <button className={styles.btn} type="submit" disabled={!isTableCodeValid(roomCode)}>
            {t.joinGame}
          </button>
          <button className={styles.btnSecondary} type="button" onClick={goHome}>
            {t.back}
          </button>
        </form>
      )}

      {/* Privacy and terms are not here any more: they are a page, linked at the
          right-hand end of the footer this screen sits above (GamePage.astro).
          A policy has to be linkable, and the entry screen is the one screen
          that footer is visible on anyway. */}

      {showRules && <RulesModal onClose={() => setShowRules(false)} />}
    </div>
  )
}
