// client/src/components/WaitingRoom.svelte
<script lang="ts">
  import type { PlayerDTO, ClientMsg, MatchFormat } from '../types/protocol'
  import { i18n } from '../i18n/i18n.svelte'
  import RulesButton from './RulesButton.svelte'
  import RulesModal from './RulesModal.svelte'
  import Preferences from './Preferences.svelte'
  import TableCode from './TableCode.svelte'
  import { tableInviteUrl } from '../hooks/tableInvite'
  import AudioSettings from './AudioSettings.svelte'
  import { seatColor, seatInitial } from './playerColors'

  type Props = {
    roomCode: string
    players: PlayerDTO[]
    myIndex: number
    matchFormat: MatchFormat
    maxPlayers: number
    onSend: (msg: ClientMsg) => void
    onLeave: () => void
    /**
     * Showcase only: mounts straight into the confirmation, which is otherwise
     * component-local state no scene could reach. Same trick as Lobby's
     * `initialMode`.
     */
    initialConfirmLeave?: boolean
  }

  let {
    roomCode,
    players,
    myIndex,
    matchFormat,
    maxPlayers,
    onSend,
    onLeave,
    initialConfirmLeave = false,
  }: Props = $props()

  const MATCH_FORMATS: MatchFormat[] = ['BO1', 'BO3', 'BO5', 'BO7']

  // Mirrors the server's serverMinPlayers / serverMaxPlayers (game/room.go). A cap
  // of 1 is a room that can never start, so the field must not even offer it.
  const MIN_PLAYERS = 2
  const MAX_PLAYERS = 10

  const t = $derived(i18n.t)
  const isOwner = $derived(myIndex === 0)
  const canStart = $derived(players.length >= 2)

  let maxInput = $state(String(maxPlayers))
  let showRules = $state(false)
  let copied = $state(false)
  let confirmLeave = $state(initialConfirmLeave)

  // Escape backs out of the question, like every other dismissible thing here.
  // Bound while the question is up and only then: a listener that outlives it
  // would swallow the key from whatever comes next.
  $effect(() => {
    if (!confirmLeave) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') confirmLeave = false
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  })

  // What the press copies is the link, not the six characters. A code has to be
  // read, retyped without a slip and typed into a screen the other person has to
  // find first; a link is a tap. The code itself stays on screen, because it is
  // what gets read out loud on a stream and what somebody already sitting in the
  // lobby types.
  //
  // The link carries no language. It gets forwarded, and the sender does not know
  // who ends up pressing it; the language is whoever opens it to choose.
  //
  // Clipboard is unavailable on insecure origins and in some embedded views;
  // failing silently is correct here — the code stays visible either way.
  function copyCode() {
    navigator.clipboard?.writeText(tableInviteUrl(roomCode)).then(
      () => {
        copied = true
        setTimeout(() => (copied = false), 1600)
      },
      () => {},
    )
  }

  const FORMAT_LABEL: Record<MatchFormat, string> = $derived({
    BO1: t.bestOf1,
    BO3: t.bestOf3,
    BO5: t.bestOf5,
    BO7: t.bestOf7,
  })

  const minAllowed = $derived(Math.max(MIN_PLAYERS, players.length))

  function handleMaxPlayersChange(val: string) {
    maxInput = val
    const n = parseInt(val, 10)
    if (!isNaN(n) && n >= minAllowed && n <= MAX_PLAYERS) {
      onSend({ type: 'set_max_players', max_players: n })
    }
  }

  // Typing an out-of-range value leaves the field showing something the server
  // never accepted; snapping back on blur is what tells the host the change did
  // not take.
  function handleMaxPlayersBlur() {
    const n = parseInt(maxInput, 10)
    if (isNaN(n) || n < minAllowed || n > MAX_PLAYERS) maxInput = String(maxPlayers)
  }
</script>

<div class="container">
  <div class="topBar">
    <Preferences />
    <AudioSettings />
    <RulesButton label={t.rulesBtn} onclick={() => (showRules = true)} />
  </div>

  <h2 class="heading">{t.waitingRoom}</h2>
  <!-- Tap-to-copy, and what lands in the clipboard is the link. The code is still
       what a stream reads out, so it stays the thing on screen; the press is for
       the other way in, the one nobody has to type. -->
  <button
    class="code"
    onclick={copyCode}
    title={t.copyLink}
    aria-label="{t.roomCode} {roomCode}. {t.copyLink}"
  >
    <span class={copied ? 'copied' : undefined}>{copied ? t.copyCode : t.roomCode}</span>
    <TableCode code={roomCode} class="codeVal" />
  </button>
  <p class="hint">{t.shareCode}</p>

  <ul class="playerList">
    {#each players as p (p.index)}
      <li class="player">
        <span class="playerMain">
          <span class="avatar" style="background: {seatColor(p.index)}" aria-hidden="true">
            {seatInitial(p.nickname)}
          </span>
          <span class="playerName" class:you={p.index === myIndex}>{p.nickname}</span>
        </span>
        {#if p.index === 0}
          <span class="owner">{t.hostBadge}</span>
        {/if}
        <!-- The host's control over one row. Never on their own: giving up the
             seat you are sitting in is the link at the bottom, and a kick that
             could do it would hand the table away silently.

             No confirmation, deliberately: this table's one question is the one
             about leaving, and unlike leaving a mistake here costs nothing — the
             code is still in the removed player's hands and they sit back down. -->
        {#if isOwner && p.index !== myIndex}
          <button
            class="kick"
            aria-label="{t.kickPlayer}: {p.nickname}"
            title={t.kickPlayer}
            onclick={() => onSend({ type: 'kick_player', target_index: p.index })}
          >
            <!-- Drawn, not a glyph: a `×` is a different object on every platform
                 and lands somewhere between a multiplication sign and a letter.
                 Same rule as the preference icons. -->
            <svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true" focusable="false">
              <path
                d="M6 6 L18 18 M18 6 L6 18"
                fill="none"
                stroke="currentColor"
                stroke-width="3"
                stroke-linecap="round"
              />
            </svg>
          </button>
        {/if}
      </li>
    {/each}
  </ul>

  {#if isOwner}
    <div class="hostConfig">
      <div class="configRow">
        <label class="configLabel" for="loco-format">{t.matchFormat}</label>
        <div class="formatBtns" id="loco-format">
          {#each MATCH_FORMATS as f (f)}
            <button
              class="formatBtn"
              class:formatBtnActive={matchFormat === f}
              onclick={() => onSend({ type: 'set_match_format', match_format: f })}
            >
              {FORMAT_LABEL[f]}
            </button>
          {/each}
        </div>
      </div>
      <div class="configRow">
        <label class="configLabel" for="loco-max-players">{t.maxPlayersLabel}</label>
        <input
          id="loco-max-players"
          type="number"
          min={minAllowed}
          max={MAX_PLAYERS}
          value={maxInput}
          oninput={(e) => handleMaxPlayersChange(e.currentTarget.value)}
          onblur={handleMaxPlayersBlur}
          class="maxInput"
        />
      </div>
    </div>
  {:else}
    <div class="configDisplay">
      <span>{t.matchFormat}: <strong>{FORMAT_LABEL[matchFormat]}</strong></span>
      <span>{t.maxPlayersLabel}: <strong>{maxPlayers}</strong></span>
    </div>
  {/if}

  {#if isOwner}
    <div class="hostActions">
      <button
        class="btnSecondary"
        disabled={players.length >= maxPlayers}
        onclick={() => onSend({ type: 'add_bot' })}
      >
        {t.addBot}
      </button>
      <button class="btn" disabled={!canStart} onclick={() => onSend({ type: 'start_game' })}>
        {canStart ? t.startGame : t.waitingForPlayers}
      </button>
    </div>
  {:else}
    <p class="waitingMsg">{t.waitingForHost}</p>
  {/if}

  <!-- Nothing has been dealt yet, so leaving is free: the server frees the seat on
       the spot instead of holding it 60s the way a closed tab would. Kept quiet on
       purpose — it must never compete with Start.

       It still asks first: the press is one-way, and on this screen it also costs
       the table code, which a guest has no way to get back. The question takes the
       link's place rather than opening over it, so the answer is where the finger
       already is and nothing else on the screen moves. -->
  {#if confirmLeave}
    <div class="leaveConfirm">
      <p class="leaveConfirmMsg">{t.leaveConfirm}</p>
      <div class="leaveConfirmBtns">
        <!-- Staying comes first and is the solid one: the safe answer should be
             the easy one to hit. -->
        <!-- svelte-ignore a11y_autofocus -->
        <button class="leaveStay" onclick={() => (confirmLeave = false)} autofocus>
          {t.leaveConfirmStay}
        </button>
        <button class="leaveGo" onclick={onLeave}>{t.leaveConfirmYes}</button>
      </div>
    </div>
  {:else}
    <button class="leaveBtn" onclick={() => (confirmLeave = true)}>{t.leaveRoom}</button>
  {/if}

  {#if showRules}
    <RulesModal onClose={() => (showRules = false)} />
  {/if}
</div>

<style>
  /* Pre-game room. The room code is the single most-read thing on this screen —
     people say it out loud on stream — so it gets plaque treatment. */

  .container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    /* See Lobby.svelte — `safe` prevents the heading being clipped above the
       scroll area once the roster and host panel exceed the viewport. */
    justify-content: safe center;
    height: 100%;
    gap: var(--space-md);
    padding: calc(var(--space-xl) + var(--safe-top)) calc(var(--space-base) + var(--safe-right))
      calc(var(--space-lg) + var(--safe-bottom)) calc(var(--space-base) + var(--safe-left));
    overflow-y: auto;
    position: relative;
    background: transparent;
    color: var(--color-ink);
    font-family: var(--font-body);
  }

  .topBar {
    position: absolute;
    top: calc(var(--space-base) + var(--safe-top));
    right: calc(var(--space-base) + var(--safe-right));
    display: flex;
    align-items: center;
    gap: var(--space-sm);
    z-index: 5;
  }

  /* The rules opener is <RulesButton />, which carries its own chip styling. */

  .heading {
    font: 700 26px/1.15 var(--font-display);
    color: var(--color-ink);
  }

  /* Room-code plaque */
  .code {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 2px;
    padding: 10px 30px 14px;
    background: var(--color-surface-card);
    border: var(--stroke) solid var(--color-stroke);
    border-radius: var(--radius-lg);
    box-shadow: var(--shadow-hard-lg);
    font: 700 12px/1.3 var(--font-display);
    color: var(--color-muted);
    text-transform: uppercase;
    letter-spacing: 0.1em;
    text-align: center;
    cursor: pointer;
    transition:
      transform 0.12s var(--ease-bounce),
      box-shadow 0.12s var(--ease-out);
  }

  .code:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 0 var(--color-stroke-soft);
  }
  .code:active {
    transform: translateY(3px);
    box-shadow: 0 2px 0 var(--color-stroke-soft);
  }

  /* Global because the element wearing it is rendered by <TableCode />, the one
     component allowed to print a table code. */
  .code :global(.codeVal) {
    font: 700 clamp(34px, 8vw, 46px) / 1.1 var(--font-display);
    color: var(--color-primary);
    letter-spacing: 0.14em;
    display: block;
    text-align: center;
    -webkit-text-stroke: 2px var(--color-stroke);
    paint-order: stroke fill;
  }

  .copied {
    color: var(--color-mint);
  }

  .hint {
    font: 500 14px/1.4 var(--font-body);
    color: var(--color-muted);
  }

  .playerList {
    list-style: none;
    display: flex;
    flex-direction: column;
    gap: 6px;
    width: 340px;
    max-width: 100%;
  }

  .player {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: var(--space-md);
    padding: 8px 14px;
    background: var(--color-surface-card);
    border: var(--stroke) solid var(--color-stroke);
    border-radius: var(--radius-full);
    box-shadow: 0 3px 0 var(--color-stroke-soft);
    font: 600 16px/1.3 var(--font-display);
    color: var(--color-ink);
    animation: playerIn 0.32s var(--ease-bounce) both;
  }

  .playerMain {
    display: flex;
    align-items: center;
    gap: 10px;
    min-width: 0;
  }

  /* Initial-letter avatar. Hue is derived from the seat index in the component, so
     the same player keeps the same colour for the whole match. */
  .avatar {
    width: 34px;
    height: 34px;
    flex-shrink: 0;
    border-radius: var(--radius-full);
    border: var(--stroke-thin) solid var(--color-stroke);
    display: flex;
    align-items: center;
    justify-content: center;
    font: 700 16px/1 var(--font-display);
    color: var(--color-on-dark);
    text-shadow: 0 1px 2px rgba(20, 8, 45, 0.5);
  }

  .playerName {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  @keyframes playerIn {
    from {
      opacity: 0;
      transform: translateY(-8px) scale(0.94);
    }
    to {
      opacity: 1;
      transform: translateY(0) scale(1);
    }
  }

  .you {
    color: var(--color-primary);
    font-weight: 700;
  }

  .owner {
    font: 700 11px/1.2 var(--font-display);
    background: var(--gradient-secondary);
    color: var(--color-on-secondary);
    padding: 4px 10px;
    border-radius: var(--radius-full);
    letter-spacing: 0.05em;
    text-transform: uppercase;
    border: var(--stroke-thin) solid var(--color-stroke);
    flex-shrink: 0;
  }

  /* The host's per-row control. Quiet until it is looked at: it sits on every row
     but one and must never compete with the roster it is attached to. The touch
     target is a full 44px while the ink stays small. */
  .kick {
    flex-shrink: 0;
    width: 44px;
    height: 44px;
    margin: -5px -8px -5px 0;
    display: flex;
    align-items: center;
    justify-content: center;
    border: none;
    background: none;
    border-radius: var(--radius-full);
    color: var(--color-muted);
    cursor: pointer;
    touch-action: manipulation;
    transition:
      color 0.12s var(--ease-out),
      background 0.12s var(--ease-out);
  }

  .kick:hover,
  .kick:focus-visible {
    color: var(--color-primary);
    background: var(--color-surface-strong);
  }

  .btn {
    padding: 14px 30px;
    min-height: 54px;
    border-radius: var(--radius-full);
    border: var(--stroke) solid var(--color-stroke);
    background: var(--gradient-primary);
    color: var(--color-on-primary);
    text-shadow: 0 2px 0 rgba(120, 10, 40, 0.4);
    font: 700 19px/1.2 var(--font-display);
    cursor: pointer;
    box-shadow: 0 5px 0 var(--color-stroke-soft);
    transition:
      transform 0.12s var(--ease-bounce),
      box-shadow 0.12s var(--ease-out),
      filter 0.12s ease;
    touch-action: manipulation;
  }

  .btn:hover:not(:disabled) {
    transform: translateY(-3px);
    box-shadow: 0 8px 0 var(--color-stroke-soft);
    filter: brightness(1.06);
  }
  .btn:active:not(:disabled) {
    transform: translateY(3px);
    box-shadow: 0 2px 0 var(--color-stroke-soft);
  }

  .btn:disabled {
    background: var(--color-surface-strong);
    color: var(--color-muted);
    cursor: not-allowed;
    box-shadow: none;
    text-shadow: none;
  }

  .waitingMsg {
    color: var(--color-muted);
    font: 600 15px/1.4 var(--font-body);
  }

  .hostActions {
    display: flex;
    flex-direction: column;
    gap: var(--space-sm);
    align-items: center;
  }

  .btnSecondary {
    padding: 12px 24px;
    min-height: 48px;
    border-radius: var(--radius-full);
    border: var(--stroke) solid var(--color-stroke);
    background: var(--color-surface-card);
    color: var(--color-ink);
    font: 600 15px/1.2 var(--font-display);
    cursor: pointer;
    box-shadow: 0 4px 0 var(--color-stroke-soft);
    transition:
      transform 0.12s var(--ease-bounce),
      box-shadow 0.12s var(--ease-out);
    touch-action: manipulation;
  }

  .btnSecondary:hover:not(:disabled) {
    transform: translateY(-2px);
    box-shadow: 0 6px 0 var(--color-stroke-soft);
  }
  .btnSecondary:active:not(:disabled) {
    transform: translateY(2px);
    box-shadow: 0 2px 0 var(--color-stroke-soft);
  }

  /* The same recipe as `.btn:disabled` twenty lines up: a fill swap, a muted
     label and no ledge. It was an opacity, which made the two disabled buttons on
     this one screen two different objects. */
  .btnSecondary:disabled {
    background: var(--color-surface-strong);
    color: var(--color-muted);
    cursor: not-allowed;
    box-shadow: none;
  }

  /* The way out. Underlined text rather than a plaque: it is always available and
     never the thing to press, so it carries no raised-object treatment. */
  .leaveBtn {
    margin-top: var(--space-xs);
    padding: 8px 14px;
    min-height: 40px;
    border: none;
    background: none;
    color: var(--color-muted);
    font: 600 14px/1.2 var(--font-display);
    text-decoration: underline;
    text-underline-offset: 3px;
    cursor: pointer;
    touch-action: manipulation;
    transition: color 0.12s var(--ease-out);
  }

  .leaveBtn:hover {
    color: var(--color-ink);
  }

  /* The question, in the link's place. It is allowed to be louder than the link
     was: at this point it is the only thing being asked. */
  .leaveConfirm {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: var(--space-sm);
    margin-top: var(--space-xs);
    padding: var(--space-sm) var(--space-base);
    background: var(--color-surface-card);
    border: var(--stroke) solid var(--color-stroke);
    border-radius: var(--radius-lg);
    box-shadow: var(--shadow-hard-lg);
    animation: confirmIn 0.18s var(--ease-bounce) both;
  }

  @keyframes confirmIn {
    from {
      opacity: 0;
      transform: translateY(6px) scale(0.97);
    }
    to {
      opacity: 1;
      transform: translateY(0) scale(1);
    }
  }

  .leaveConfirmMsg {
    font: 700 16px/1.3 var(--font-display);
    color: var(--color-ink);
    text-align: center;
  }

  .leaveConfirmBtns {
    display: flex;
    gap: var(--space-sm);
  }

  .leaveStay,
  .leaveGo {
    padding: 10px 20px;
    min-height: 44px;
    border-radius: var(--radius-full);
    border: var(--stroke) solid var(--color-stroke);
    font: 700 15px/1.2 var(--font-display);
    cursor: pointer;
    box-shadow: 0 4px 0 var(--color-stroke-soft);
    transition:
      transform 0.12s var(--ease-bounce),
      box-shadow 0.12s var(--ease-out);
    touch-action: manipulation;
  }

  .leaveStay {
    background: var(--gradient-tertiary);
    color: var(--color-on-dark);
    text-shadow: 0 1px 0 rgba(30, 10, 90, 0.4);
  }

  /* Leaving stays plain: it is the answer that costs something, so it does not get
     the colour that reads as "press me". */
  .leaveGo {
    background: var(--color-surface-strong);
    color: var(--color-body);
  }

  .leaveStay:hover,
  .leaveGo:hover {
    transform: translateY(-2px);
    box-shadow: 0 6px 0 var(--color-stroke-soft);
  }
  .leaveStay:active,
  .leaveGo:active {
    transform: translateY(2px);
    box-shadow: 0 2px 0 var(--color-stroke-soft);
  }

  :root[data-motion="reduce"] .leaveConfirm {
    animation: none;
  }

  /* Host config panel */
  .hostConfig {
    display: flex;
    flex-direction: column;
    gap: var(--space-md);
    width: 340px;
    max-width: 100%;
    background: var(--color-surface-card);
    border: var(--stroke) solid var(--color-stroke);
    border-radius: var(--radius-lg);
    padding: var(--space-base) var(--space-lg);
    box-shadow: var(--shadow-hard-lg);
  }

  .configRow {
    display: flex;
    flex-direction: column;
    gap: var(--space-sm);
  }

  .configLabel {
    font: 700 12px/1.2 var(--font-display);
    color: var(--color-muted);
    text-transform: uppercase;
    letter-spacing: 0.08em;
  }

  .formatBtns {
    display: flex;
    gap: 6px;
    flex-wrap: wrap;
  }

  .formatBtn {
    padding: 10px 14px;
    border-radius: var(--radius-full);
    border: var(--stroke-thin) solid var(--color-stroke);
    background: var(--color-surface-strong);
    color: var(--color-ink);
    font: 600 14px/1.2 var(--font-display);
    cursor: pointer;
    min-height: 42px;
    touch-action: manipulation;
    box-shadow: 0 3px 0 var(--color-stroke-soft);
    transition:
      transform 0.12s var(--ease-bounce),
      box-shadow 0.12s var(--ease-out),
      background 0.15s;
  }

  .formatBtn:hover {
    transform: translateY(-2px);
    box-shadow: 0 5px 0 var(--color-stroke-soft);
  }
  .formatBtn:active {
    transform: translateY(2px);
    box-shadow: 0 1px 0 var(--color-stroke-soft);
  }

  .formatBtnActive {
    background: var(--gradient-tertiary);
    color: var(--color-on-dark);
    text-shadow: 0 1px 0 rgba(30, 10, 90, 0.4);
  }

  .maxInput {
    padding: 10px 14px;
    border-radius: var(--radius-md);
    border: var(--stroke) solid var(--color-stroke);
    background: var(--color-surface-strong);
    color: var(--color-ink);
    font: 700 17px/1.3 var(--font-display);
    width: 90px;
    min-height: 46px;
    box-shadow: inset 0 3px 0 rgba(36, 21, 70, 0.08);
  }

  .maxInput:focus {
    outline: none;
    box-shadow:
      inset 0 3px 0 rgba(36, 21, 70, 0.08),
      0 0 0 4px rgba(108, 92, 255, 0.35);
  }

  .configDisplay {
    display: flex;
    gap: var(--space-md);
    flex-wrap: wrap;
    justify-content: center;
    color: var(--color-body);
    font: 500 14px/1.4 var(--font-body);
  }

  .configDisplay span {
    padding: 6px 14px;
    background: var(--color-surface-card);
    border: var(--stroke-thin) solid var(--color-stroke);
    border-radius: var(--radius-full);
  }

  @media (max-width: 480px) {
    .hostConfig,
    .playerList {
      width: 100%;
      max-width: 340px;
    }

    .formatBtn {
      flex: 1;
      min-width: 0;
      text-align: center;
      padding: 10px 6px;
    }
  }

  :root[data-motion="reduce"] .player {
    animation: none;
  }
</style>

// client/src/components/WaitingRoom.tsx
import { useEffect, useState } from 'react'
import { PlayerDTO, ClientMsg, MatchFormat } from '../types/protocol'
import { useI18n } from '../i18n'
import { RulesButton } from './RulesButton'
import { RulesModal } from './RulesModal'
import { Preferences } from './Preferences'
import { TableCode } from './TableCode'
import { tableInviteUrl } from '../hooks/tableInvite'
import { AudioSettings } from './AudioSettings'
import { seatColor, seatInitial } from './playerColors'
import styles from './WaitingRoom.module.css'

interface Props {
  roomCode: string
  players: PlayerDTO[]
  myIndex: number
  matchFormat: MatchFormat
  maxPlayers: number
  onSend: (msg: ClientMsg) => void
  onLeave: () => void
  /** Showcase only: mounts straight into the confirmation, which is otherwise
   *  component-local state no scene could reach. Same trick as Lobby's
   *  `initialMode`. */
  initialConfirmLeave?: boolean
}

const MATCH_FORMATS: MatchFormat[] = ['BO1', 'BO3', 'BO5', 'BO7']

// Drawn, not a glyph: a `×` is a different object on every platform and lands
// somewhere between a multiplication sign and a letter. Same rule as the
// preference icons.
function KickIcon() {
  return (
    <svg viewBox="0 0 24 24" width="14" height="14" aria-hidden focusable="false">
      <path
        d="M6 6 L18 18 M18 6 L6 18"
        fill="none"
        stroke="currentColor"
        strokeWidth="3"
        strokeLinecap="round"
      />
    </svg>
  )
}

// Mirrors the server's serverMinPlayers / serverMaxPlayers (game/room.go). A cap of 1
// is a room that can never start, so the field must not even offer it.
const MIN_PLAYERS = 2
const MAX_PLAYERS = 10

export function WaitingRoom({
  roomCode,
  players,
  myIndex,
  matchFormat,
  maxPlayers,
  onSend,
  onLeave,
  initialConfirmLeave = false,
}: Props) {
  const { t } = useI18n()
  const isOwner = myIndex === 0
  const canStart = players.length >= 2
  const [maxInput, setMaxInput] = useState<string>(String(maxPlayers))
  const [showRules, setShowRules] = useState(false)
  const [copied, setCopied] = useState(false)
  const [confirmLeave, setConfirmLeave] = useState(initialConfirmLeave)

  // Escape backs out of the question, like every other dismissible thing here.
  // Bound while the question is up and only then: a listener that outlives it
  // would swallow the key from whatever comes next.
  useEffect(() => {
    if (!confirmLeave) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setConfirmLeave(false)
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [confirmLeave])

  // What the press copies is the link, not the six characters. A code has to be
  // read, retyped without a slip and typed into a screen the other person has
  // to find first; a link is a tap. The code itself stays on screen, because it
  // is what gets read out loud on a stream and what somebody already sitting in
  // the lobby types.
  //
  // The link carries no language. It gets forwarded, and the sender does not
  // know who ends up pressing it; the language is whoever opens it to choose.
  //
  // Clipboard is unavailable on insecure origins and in some embedded views;
  // failing silently is correct here — the code stays visible either way.
  const copyCode = () => {
    navigator.clipboard?.writeText(tableInviteUrl(roomCode)).then(
      () => {
        setCopied(true)
        setTimeout(() => setCopied(false), 1600)
      },
      () => {},
    )
  }

  const FORMAT_LABEL: Record<MatchFormat, string> = {
    BO1: t.bestOf1,
    BO3: t.bestOf3,
    BO5: t.bestOf5,
    BO7: t.bestOf7,
  }

  const minAllowed = Math.max(MIN_PLAYERS, players.length)

  const handleMaxPlayersChange = (val: string) => {
    setMaxInput(val)
    const n = parseInt(val, 10)
    if (!isNaN(n) && n >= minAllowed && n <= MAX_PLAYERS) {
      onSend({ type: 'set_max_players', max_players: n })
    }
  }

  // Typing an out-of-range value leaves the field showing something the server never
  // accepted; snapping back on blur is what tells the host the change did not take.
  const handleMaxPlayersBlur = () => {
    const n = parseInt(maxInput, 10)
    if (isNaN(n) || n < minAllowed || n > MAX_PLAYERS) setMaxInput(String(maxPlayers))
  }

  return (
    <div className={styles.container}>
      <div className={styles.topBar}>
        <Preferences />
        <AudioSettings />
        <RulesButton label={t.rulesBtn} onClick={() => setShowRules(true)} />
      </div>

      <h2 className={styles.heading}>{t.waitingRoom}</h2>
      {/* Tap-to-copy, and what lands in the clipboard is the link. The code is
          still what a stream reads out, so it stays the thing on screen; the
          press is for the other way in, the one nobody has to type. */}
      <button
        className={styles.code}
        onClick={copyCode}
        title={t.copyLink}
        aria-label={`${t.roomCode} ${roomCode}. ${t.copyLink}`}
      >
        <span className={copied ? styles.copied : undefined}>{copied ? t.copyCode : t.roomCode}</span>
        <TableCode code={roomCode} className={styles.codeVal} />
      </button>
      <p className={styles.hint}>{t.shareCode}</p>

      <ul className={styles.playerList}>
        {players.map((p) => (
          <li key={p.index} className={styles.player}>
            <span className={styles.playerMain}>
              <span className={styles.avatar} style={{ background: seatColor(p.index) }} aria-hidden>
                {seatInitial(p.nickname)}
              </span>
              <span className={`${styles.playerName} ${p.index === myIndex ? styles.you : ''}`}>
                {p.nickname}
              </span>
            </span>
            {p.index === 0 && <span className={styles.owner}>{t.hostBadge}</span>}
            {/* The host's control over one row. Never on their own: giving up
                the seat you are sitting in is the link at the bottom, and a
                kick that could do it would hand the table away silently.

                No confirmation, deliberately: this table's one question is the
                one about leaving, and unlike leaving a mistake here costs
                nothing — the code is still in the removed player's hands and
                they sit back down. */}
            {isOwner && p.index !== myIndex && (
              <button
                className={styles.kick}
                aria-label={`${t.kickPlayer}: ${p.nickname}`}
                title={t.kickPlayer}
                onClick={() => onSend({ type: 'kick_player', target_index: p.index })}
              >
                <KickIcon />
              </button>
            )}
          </li>
        ))}
      </ul>

      {isOwner && (
        <div className={styles.hostConfig}>
          <div className={styles.configRow}>
            <label className={styles.configLabel}>{t.matchFormat}</label>
            <div className={styles.formatBtns}>
              {MATCH_FORMATS.map((f) => (
                <button
                  key={f}
                  className={`${styles.formatBtn} ${matchFormat === f ? styles.formatBtnActive : ''}`}
                  onClick={() => onSend({ type: 'set_match_format', match_format: f })}
                >
                  {FORMAT_LABEL[f]}
                </button>
              ))}
            </div>
          </div>
          <div className={styles.configRow}>
            <label className={styles.configLabel}>{t.maxPlayersLabel}</label>
            <input
              type="number"
              min={minAllowed}
              max={MAX_PLAYERS}
              value={maxInput}
              onChange={(e) => handleMaxPlayersChange(e.target.value)}
              onBlur={handleMaxPlayersBlur}
              className={styles.maxInput}
            />
          </div>
        </div>
      )}

      {!isOwner && (
        <div className={styles.configDisplay}>
          <span>{t.matchFormat}: <strong>{FORMAT_LABEL[matchFormat]}</strong></span>
          <span>{t.maxPlayersLabel}: <strong>{maxPlayers}</strong></span>
        </div>
      )}

      {isOwner && (
        <div className={styles.hostActions}>
          <button
            className={styles.btnSecondary}
            disabled={players.length >= maxPlayers}
            onClick={() => onSend({ type: 'add_bot' })}
          >
            {t.addBot}
          </button>
          <button
            className={styles.btn}
            disabled={!canStart}
            onClick={() => onSend({ type: 'start_game' })}
          >
            {canStart ? t.startGame : t.waitingForPlayers}
          </button>
        </div>
      )}
      {!isOwner && (
        <p className={styles.waitingMsg}>{t.waitingForHost}</p>
      )}

      {/* Nothing has been dealt yet, so leaving is free: the server frees the seat
          on the spot instead of holding it 60s the way a closed tab would. Kept
          quiet on purpose — it must never compete with Start.

          It still asks first: the press is one-way, and on this screen it also
          costs the table code, which a guest has no way to get back. The question
          takes the link's place rather than opening over it, so the answer is
          where the finger already is and nothing else on the screen moves. */}
      {confirmLeave ? (
        <div className={styles.leaveConfirm}>
          <p className={styles.leaveConfirmMsg}>{t.leaveConfirm}</p>
          <div className={styles.leaveConfirmBtns}>
            {/* Staying comes first and is the solid one: the safe answer should
                be the easy one to hit. */}
            <button
              className={styles.leaveStay}
              onClick={() => setConfirmLeave(false)}
              autoFocus
            >
              {t.leaveConfirmStay}
            </button>
            <button className={styles.leaveGo} onClick={onLeave}>
              {t.leaveConfirmYes}
            </button>
          </div>
        </div>
      ) : (
        <button className={styles.leaveBtn} onClick={() => setConfirmLeave(true)}>
          {t.leaveRoom}
        </button>
      )}

      {showRules && <RulesModal onClose={() => setShowRules(false)} />}
    </div>
  )
}
